plugins { id 'com.android.application' }

android {
    namespace 'com.naten.advancedmobile'
    compileSdk 35

    defaultConfig {
        applicationId 'com.naten.advancedmobile.v12'
        minSdk 23
        targetSdk 33
        versionCode 12
        versionName '1.2.0'
    }

    buildTypes {
        debug {
            minifyEnabled false
            debuggable true
        }
        release {
            minifyEnabled false
            debuggable false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
